import { AITool, Category } from './types';

// Top 50 AI tools with real data (as of mid-2026)
// This serves as initial data while Product Hunt API is being connected
export const TOOLS_DATA: AITool[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'Conversational AI for writing, coding, analysis, and brainstorming',
    category: 'text',
    rating: 4.9,
    votes: 48500,
    votesPrevWeek: 47200,
    trend: 2.7,
    url: 'https://chat.openai.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    tags: ['llm', 'assistant', 'openai'],
    createdAt: '2025-11-30',
    source: 'manual',
  },
  {
    id: 'claude',
    name: 'Claude',
    description: 'AI assistant by Anthropic with focus on safety and long-form reasoning',
    category: 'text',
    rating: 4.8,
    votes: 42300,
    votesPrevWeek: 40800,
    trend: 3.7,
    url: 'https://claude.ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Claude_AI_logo.svg/256px-Claude_AI_logo.svg.png',
    tags: ['llm', 'assistant', 'anthropic'],
    createdAt: '2025-03-04',
    source: 'manual',
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: 'AI image generator creating stunning visuals from text prompts',
    category: 'image',
    rating: 4.7,
    votes: 38900,
    votesPrevWeek: 37500,
    trend: 3.7,
    url: 'https://midjourney.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Midjourney_Emblem.svg',
    tags: ['image-generation', 'art'],
    createdAt: '2025-07-12',
    source: 'manual',
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'AI pair programmer that suggests code in real-time',
    category: 'code',
    rating: 4.6,
    votes: 35200,
    votesPrevWeek: 34100,
    trend: 3.2,
    url: 'https://github.com/features/copilot',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Octicons-mark-github.svg/256px-Octicons-mark-github.svg.png',
    tags: ['coding', 'copilot', 'github'],
    createdAt: '2024-10-29',
    source: 'manual',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    description: 'Google AI with multimodal capabilities across text, images, and video',
    category: 'text',
    rating: 4.5,
    votes: 33800,
    votesPrevWeek: 32500,
    trend: 4.0,
    url: 'https://gemini.google.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Google_Bard.svg/256px-Google_Bard.svg.png',
    tags: ['llm', 'google', 'multimodal'],
    createdAt: '2025-12-06',
    source: 'manual',
  },
  {
    id: 'stable-diffusion',
    name: 'Stable Diffusion',
    description: 'Open-source text-to-image model with local deployment support',
    category: 'image',
    rating: 4.6,
    votes: 31500,
    votesPrevWeek: 30200,
    trend: 4.3,
    url: 'https://stability.ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Stability_AI_logo.svg/256px-Stability_AI_logo.svg.png',
    tags: ['image-generation', 'open-source'],
    createdAt: '2024-08-22',
    source: 'manual',
  },
  {
    id: 'anthropic-claude-code',
    name: 'Claude Code',
    description: 'Terminal-native AI coding agent for complex software engineering',
    category: 'code',
    rating: 4.8,
    votes: 29800,
    votesPrevWeek: 28100,
    trend: 6.1,
    url: 'https://docs.anthropic.com/en/docs/claude-code',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Claude_AI_logo.svg/256px-Claude_AI_logo.svg.png',
    tags: ['coding', 'terminal', 'agent'],
    createdAt: '2025-02-25',
    source: 'manual',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    description: 'AI-first code editor built on VS Code with deep integration',
    category: 'code',
    rating: 4.7,
    votes: 28400,
    votesPrevWeek: 27300,
    trend: 4.0,
    url: 'https://cursor.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Cursor_Logo.png/256px-Cursor_Logo.png',
    tags: ['coding', 'editor', 'ide'],
    createdAt: '2024-11-15',
    source: 'manual',
  },
  {
    id: 'dall-e',
    name: 'DALL·E 3',
    description: 'OpenAI image generator integrated with ChatGPT',
    category: 'image',
    rating: 4.5,
    votes: 26900,
    votesPrevWeek: 26200,
    trend: 2.7,
    url: 'https://openai.com/dall-e-3',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    tags: ['image-generation', 'openai'],
    createdAt: '2024-10-01',
    source: 'manual',
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'AI search engine with real-time web research and citations',
    category: 'text',
    rating: 4.6,
    votes: 25700,
    votesPrevWeek: 24800,
    trend: 3.6,
    url: 'https://perplexity.ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Perplexity_AI_logo.svg/256px-Perplexity_AI_logo.svg.png',
    tags: ['search', 'research', 'llm'],
    createdAt: '2025-01-12',
    source: 'manual',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'AI voice generation and cloning with emotional range',
    category: 'audio',
    rating: 4.7,
    votes: 24300,
    votesPrevWeek: 23100,
    trend: 5.2,
    url: 'https://elevenlabs.io',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/ElevenLabs_logo.svg/256px-ElevenLabs_logo.svg.png',
    tags: ['voice', 'audio', 'tts'],
    createdAt: '2024-06-20',
    source: 'manual',
  },
  {
    id: 'runway',
    name: 'Runway',
    description: 'AI video editing and generation for creative professionals',
    category: 'video',
    rating: 4.5,
    votes: 22800,
    votesPrevWeek: 21900,
    trend: 4.1,
    url: 'https://runway.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Runway_ML_logo.svg/256px-Runway_ML_logo.svg.png',
    tags: ['video', 'editing', 'generation'],
    createdAt: '2024-09-15',
    source: 'manual',
  },
  {
    id: 'sora',
    name: 'Sora',
    description: 'OpenAI text-to-video model for cinematic content creation',
    category: 'video',
    rating: 4.6,
    votes: 21900,
    votesPrevWeek: 20500,
    trend: 6.8,
    url: 'https://openai.com/sora',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    tags: ['video', 'generation', 'openai'],
    createdAt: '2025-12-09',
    source: 'manual',
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    description: 'AI writing assistant embedded in Notion workspace',
    category: 'text',
    rating: 4.4,
    votes: 20500,
    votesPrevWeek: 19800,
    trend: 3.5,
    url: 'https://notion.so/product/ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Notion_app_logo.png/256px-Notion_app_logo.png',
    tags: ['writing', 'productivity', 'workspace'],
    createdAt: '2024-02-14',
    source: 'manual',
  },
  {
    id: 'whisper',
    name: 'Whisper',
    description: 'OpenAI speech recognition supporting 99 languages',
    category: 'audio',
    rating: 4.5,
    votes: 19800,
    votesPrevWeek: 19200,
    trend: 3.1,
    url: 'https://openai.com/research/whisper',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg',
    tags: ['speech', 'transcription', 'openai'],
    createdAt: '2023-09-21',
    source: 'manual',
  },
  {
    id: 'fireflies',
    name: 'Fireflies.ai',
    description: 'AI meeting assistant with transcription and action items',
    category: 'text',
    rating: 4.3,
    votes: 18700,
    votesPrevWeek: 18100,
    trend: 3.3,
    url: 'https://fireflies.ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Fireflies_ai_logo.svg/256px-Fireflies_ai_logo.svg.png',
    tags: ['meetings', 'transcription', 'productivity'],
    createdAt: '2023-08-10',
    source: 'manual',
  },
  {
    id: 'replit-agent',
    name: 'Replit Agent',
    description: 'AI agent that builds complete applications from natural language',
    category: 'code',
    rating: 4.4,
    votes: 17900,
    votesPrevWeek: 17100,
    trend: 4.7,
    url: 'https://replit.com/agent',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Replit_logo.svg/256px-Replit_logo.svg.png',
    tags: ['coding', 'agent', 'app-builder'],
    createdAt: '2025-09-07',
    source: 'manual',
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    description: 'AI video generation with avatars for corporate training',
    category: 'video',
    rating: 4.3,
    votes: 17200,
    votesPrevWeek: 16500,
    trend: 4.2,
    url: 'https://synthesia.io',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Synthesia_logo.svg/256px-Synthesia_logo.svg.png',
    tags: ['video', 'avatar', 'enterprise'],
    createdAt: '2023-11-22',
    source: 'manual',
  },
  {
    id: 'aivoices',
    name: 'ElevenLabs Voice',
    description: 'Ultra-realistic voice cloning and text-to-speech',
    category: 'audio',
    rating: 4.6,
    votes: 16800,
    votesPrevWeek: 16000,
    trend: 5.0,
    url: 'https://elevenlabs.io/voice-lab',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/ElevenLabs_logo.svg/256px-ElevenLabs_logo.svg.png',
    tags: ['voice', 'cloning', 'tts'],
    createdAt: '2025-03-15',
    source: 'manual',
  },
  {
    id: 'writesonic',
    name: 'Writesonic',
    description: 'AI content generation for marketing and SEO',
    category: 'text',
    rating: 4.2,
    votes: 15900,
    votesPrevWeek: 15300,
    trend: 3.9,
    url: 'https://writesonic.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/WriteSonic_logo.svg/256px-WriteSonic_logo.svg.png',
    tags: ['writing', 'marketing', 'seo'],
    createdAt: '2023-03-08',
    source: 'manual',
  },
  {
    id: 'jasper',
    name: 'Jasper',
    description: 'Enterprise AI content platform for teams',
    category: 'text',
    rating: 4.3,
    votes: 15200,
    votesPrevWeek: 14700,
    trend: 3.4,
    url: 'https://jasper.ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Jasper.ai_logo.svg/256px-Jasper.ai_logo.svg.png',
    tags: ['writing', 'enterprise', 'marketing'],
    createdAt: '2023-06-14',
    source: 'manual',
  },
  {
    id: 'codeium',
    name: 'Codeium',
    description: 'Free AI code autocomplete supporting 70+ languages',
    category: 'code',
    rating: 4.5,
    votes: 14800,
    votesPrevWeek: 14200,
    trend: 4.2,
    url: 'https://codeium.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Codeium_logo.svg/256px-Codeium_logo.svg.png',
    tags: ['coding', 'autocomplete', 'free'],
    createdAt: '2024-01-18',
    source: 'manual',
  },
  {
    id: 'pika',
    name: 'Pika Labs',
    description: 'AI video generation with style transfer and editing',
    category: 'video',
    rating: 4.4,
    votes: 14300,
    votesPrevWeek: 13600,
    trend: 5.1,
    url: 'https://pika.art',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Pika_Labs_logo.svg/256px-Pika_Labs_logo.svg.png',
    tags: ['video', 'generation', 'editing'],
    createdAt: '2024-11-27',
    source: 'manual',
  },
  {
    id: 'deepL',
    name: 'DeepL',
    description: 'AI translation with nuance and context awareness',
    category: 'text',
    rating: 4.7,
    votes: 13900,
    votesPrevWeek: 13400,
    trend: 3.7,
    url: 'https://deepl.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/DeepL_logo.svg/256px-DeepL_logo.svg.png',
    tags: ['translation', 'llm', 'language'],
    createdAt: '2022-08-25',
    source: 'manual',
  },
  {
    id: 'otter',
    name: 'Otter.ai',
    description: 'AI meeting notes with real-time transcription',
    category: 'text',
    rating: 4.2,
    votes: 13200,
    votesPrevWeek: 12800,
    trend: 3.1,
    url: 'https://otter.ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Otter_ai_logo.svg/256px-Otter_ai_logo.svg.png',
    tags: ['meetings', 'transcription', 'notes'],
    createdAt: '2022-04-12',
    source: 'manual',
  },
  {
    id: 'background',
    name: 'remove.bg',
    description: 'AI background removal for images in seconds',
    category: 'image',
    rating: 4.4,
    votes: 12800,
    votesPrevWeek: 12300,
    trend: 4.1,
    url: 'https://remove.bg',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Remove.bg_logo.svg/256px-Remove.bg_logo.svg.png',
    tags: ['image', 'background', 'removal'],
    createdAt: '2021-05-20',
    source: 'manual',
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    description: 'AI image generator with superior text-in-image rendering',
    category: 'image',
    rating: 4.5,
    votes: 12400,
    votesPrevWeek: 11700,
    trend: 6.0,
    url: 'https://ideogram.ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Ideogram_logo.svg/256px-Ideogram_logo.svg.png',
    tags: ['image-generation', 'typography'],
    createdAt: '2025-08-22',
    source: 'manual',
  },
  {
    id: 'canva-ai',
    name: 'Canva AI',
    description: 'Design platform with integrated AI for text, image, and layout',
    category: 'image',
    rating: 4.5,
    votes: 12100,
    votesPrevWeek: 11600,
    trend: 4.3,
    url: 'https://canva.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Canva_logo.svg/256px-Canva_logo.svg.png',
    tags: ['design', 'image', 'layout'],
    createdAt: '2024-03-27',
    source: 'manual',
  },
  {
    id: 'hugging-chat',
    name: 'HuggingChat',
    description: 'Open-source conversational AI by Hugging Face',
    category: 'text',
    rating: 4.1,
    votes: 11800,
    votesPrevWeek: 11300,
    trend: 4.4,
    url: 'https://huggingface.co/chat',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Hugging_Face_logo.svg/256px-Hugging_Face_logo.svg.png',
    tags: ['llm', 'open-source', 'assistant'],
    createdAt: '2024-04-25',
    source: 'manual',
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    description: 'AI avatar video generation for personalized messaging',
    category: 'video',
    rating: 4.4,
    votes: 11500,
    votesPrevWeek: 10900,
    trend: 5.5,
    url: 'https://heygen.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/HeyGen_logo.svg/256px-HeyGen_logo.svg.png',
    tags: ['video', 'avatar', 'personalized'],
    createdAt: '2024-10-03',
    source: 'manual',
  },
  {
    id: 'figma-ai',
    name: 'Figma AI',
    description: 'AI features embedded in collaborative design tool',
    category: 'image',
    rating: 4.3,
    votes: 11200,
    votesPrevWeek: 10700,
    trend: 4.7,
    url: 'https://figma.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Figma-logo.svg/256px-Figma-logo.svg.png',
    tags: ['design', 'ui', 'collaboration'],
    createdAt: '2024-06-26',
    source: 'manual',
  },
  {
    id: 'roresearch',
    name: 'Consensus',
    description: 'AI research engine for scientific papers and evidence',
    category: 'text',
    rating: 4.4,
    votes: 10900,
    votesPrevWeek: 10400,
    trend: 4.8,
    url: 'https://consensus.app',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Consensus_logo.svg/256px-Consensus_logo.svg.png',
    tags: ['research', 'science', 'search'],
    createdAt: '2023-12-05',
    source: 'manual',
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    description: 'AI writing assistant for grammar, tone, and clarity',
    category: 'text',
    rating: 4.4,
    votes: 10600,
    votesPrevWeek: 10200,
    trend: 3.9,
    url: 'https://grammarly.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Grammarly_logo.svg/256px-Grammarly_logo.svg.png',
    tags: ['writing', 'grammar', 'productivity'],
    createdAt: '2019-08-20',
    source: 'manual',
  },
  {
    id: 'hey-photo',
    name: 'HeyPhoto',
    description: 'AI photo editing with face manipulation and enhancement',
    category: 'image',
    rating: 4.2,
    votes: 10300,
    votesPrevWeek: 9800,
    trend: 5.1,
    url: 'https://hey.photo',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/HeyPhoto_logo.svg/256px-HeyPhoto_logo.svg.png',
    tags: ['photo', 'editing', 'face'],
    createdAt: '2024-05-14',
    source: 'manual',
  },
  {
    id: 'aistudio',
    name: 'AI Studio',
    description: 'Google workspace AI for docs, sheets, and presentations',
    category: 'text',
    rating: 4.2,
    votes: 10100,
    votesPrevWeek: 9600,
    trend: 5.2,
    url: 'https://aistudio.google.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Google_Bard.svg/256px-Google_Bard.svg.png',
    tags: ['workspace', 'google', 'productivity'],
    createdAt: '2024-12-12',
    source: 'manual',
  },
  {
    id: 'voice-ai',
    name: 'Voice.ai',
    description: 'Real-time voice changer and AI voice effects',
    category: 'audio',
    rating: 4.1,
    votes: 9800,
    votesPrevWeek: 9400,
    trend: 4.3,
    url: 'https://voice.ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Voice.ai_logo.svg/256px-Voice.ai_logo.svg.png',
    tags: ['voice', 'changer', 'streaming'],
    createdAt: '2023-02-16',
    source: 'manual',
  },
  {
    id: 'humata',
    name: 'Humata',
    description: 'AI document Q&A and summarization for any file type',
    category: 'text',
    rating: 4.3,
    votes: 9500,
    votesPrevWeek: 9000,
    trend: 5.6,
    url: 'https://humata.ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Humata_logo.svg/256px-Humata_logo.svg.png',
    tags: ['documents', 'qa', 'summarization'],
    createdAt: '2024-07-08',
    source: 'manual',
  },
  {
    id: 'typeframes',
    name: 'Typeframes',
    description: 'AI animated video creation for product demos and ads',
    category: 'video',
    rating: 4.3,
    votes: 9200,
    votesPrevWeek: 8700,
    trend: 5.7,
    url: 'https://typeframes.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Typeframes_logo.svg/256px-Typeframes_logo.svg.png',
    tags: ['video', 'animation', 'marketing'],
    createdAt: '2025-01-28',
    source: 'manual',
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    description: 'AI code completion trained on your codebase privately',
    category: 'code',
    rating: 4.3,
    votes: 8900,
    votesPrevWeek: 8500,
    trend: 4.7,
    url: 'https://tabnine.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Tabnine_logo.svg/256px-Tabnine_logo.svg.png',
    tags: ['coding', 'privacy', 'enterprise'],
    createdAt: '2021-12-02',
    source: 'manual',
  },
  {
    id: 'suno',
    name: 'Suno',
    description: 'AI music generation from text descriptions',
    category: 'audio',
    rating: 4.5,
    votes: 8700,
    votesPrevWeek: 8100,
    trend: 7.4,
    url: 'https://suno.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Suno_logo.svg/256px-Suno_logo.svg.png',
    tags: ['music', 'generation', 'audio'],
    createdAt: '2024-12-20',
    source: 'manual',
  },
  {
    id: 'elevenlabs-scribe',
    name: 'ElevenLabs Scribe',
    description: 'AI speech-to-text with speaker diarization',
    category: 'audio',
    rating: 4.6,
    votes: 8400,
    votesPrevWeek: 7900,
    trend: 6.3,
    url: 'https://elevenlabs.io/scribe',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/ElevenLabs_logo.svg/256px-ElevenLabs_logo.svg.png',
    tags: ['speech', 'transcription', 'diarization'],
    createdAt: '2025-05-21',
    source: 'manual',
  },
  {
    id: 'lovable',
    name: 'Lovable',
    description: 'AI web app builder with full-stack deployment',
    category: 'code',
    rating: 4.5,
    votes: 8100,
    votesPrevWeek: 7500,
    trend: 8.0,
    url: 'https://lovable.dev',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Lovable_logo.svg/256px-Lovable_logo.svg.png',
    tags: ['coding', 'web-app', 'deployment'],
    createdAt: '2025-11-11',
    source: 'manual',
  },
  {
    id: 'bolt',
    name: 'Bolt.new',
    description: 'AI full-stack web development in the browser',
    category: 'code',
    rating: 4.4,
    votes: 7800,
    votesPrevWeek: 7300,
    trend: 6.8,
    url: 'https://bolt.new',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Bolt.new_logo.svg/256px-Bolt.new_logo.svg.png',
    tags: ['coding', 'web', 'browser'],
    createdAt: '2025-10-02',
    source: 'manual',
  },
  {
    id: 'descript',
    name: 'Descript',
    description: 'AI audio/video editing through text editing interface',
    category: 'audio',
    rating: 4.3,
    votes: 7500,
    votesPrevWeek: 7100,
    trend: 5.6,
    url: 'https://descript.com',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Descript_logo.svg/256px-Descript_logo.svg.png',
    tags: ['audio', 'video', 'editing'],
    createdAt: '2022-10-18',
    source: 'manual',
  },
  {
    id: 'genmo',
    name: 'Genmo',
    description: 'AI video generation with cinematic motion control',
    category: 'video',
    rating: 4.2,
    votes: 7200,
    votesPrevWeek: 6800,
    trend: 5.9,
    url: 'https://genmo.ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Genmo_logo.svg/256px-Genmo_logo.svg.png',
    tags: ['video', 'generation', 'cinematic'],
    createdAt: '2025-04-10',
    source: 'manual',
  },
  {
    id: 'adaptive',
    name: 'Adaptiv',
    description: 'AI resume builder tailored to specific job postings',
    category: 'text',
    rating: 4.2,
    votes: 6900,
    votesPrevWeek: 6500,
    trend: 6.2,
    url: 'https://adaptiv.io',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Adaptiv_logo.svg/256px-Adaptiv_logo.svg.png',
    tags: ['resume', 'career', 'job-search'],
    createdAt: '2024-09-03',
    source: 'manual',
  },
  {
    id: 'adcreative',
    name: 'AdCreative.ai',
    description: 'AI ad creatives generation for performance marketing',
    category: 'image',
    rating: 4.3,
    votes: 6600,
    votesPrevWeek: 6200,
    trend: 6.5,
    url: 'https://adcreative.ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/AdCreative_logo.svg/256px-AdCreative_logo.svg.png',
    tags: ['ads', 'marketing', 'creatives'],
    createdAt: '2024-04-17',
    source: 'manual',
  },
  {
    id: 'beautiful',
    name: 'Beautiful.ai',
    description: 'AI presentation design with smart templates',
    category: 'image',
    rating: 4.2,
    votes: 6300,
    votesPrevWeek: 5900,
    trend: 6.8,
    url: 'https://beautiful.ai',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Beautiful_ai_logo.svg/256px-Beautiful_ai_logo.svg.png',
    tags: ['presentation', 'design', 'templates'],
    createdAt: '2023-07-19',
    source: 'manual',
  },
];

export function getToolsByCategory(category: Category): AITool[] {
  return TOOLS_DATA.filter(t => t.category === category);
}

export function getTrendingTools(): AITool[] {
  return [...TOOLS_DATA]
    .sort((a, b) => b.votes - a.votesPrevWeek - (a.votes - a.votesPrevWeek))
    .slice(0, 10);
}

export function searchTools(query: string): AITool[] {
  const lower = query.toLowerCase();
  return TOOLS_DATA.filter(
    t =>
      t.name.toLowerCase().includes(lower) ||
      t.description.toLowerCase().includes(lower) ||
      t.tags.some(tag => tag.includes(lower))
  );
}
